# Generated by Django 5.1.3 on 2024-12-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continousintegrationanddelivery', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='Default.png', null=True, upload_to='images/'),
        ),
    ]
