version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 975050183634.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t  -f backend .
      - docker tag backend:latest 975050183634.dkr.ecr.us-east-1.amazonaws.com/danilusdjango:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker push 975050183634.dkr.ecr.us-east-1.amazonaws.com/danilusdjango:latest
      - printf '[{"name":"containerone","imageUri":"%s"}]' 975050183634.dkr.ecr.us-east-1.amazonaws.com/danilusdjango:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
